### ISSUE TITLE
DUPE: [nbpresent] Theming for static export (HTML, PDF) 

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-nb-extensions#133]
Parent design discussion issue /anaconda-server/nbpresent#34

* [ ] decision point: ship with pre-packaged themes OR provide client-side config options
* [ ] controls for unstyled font, header font, font size, header color (for headings), background color, text color
* [ ] theme must carry thru to static HTML/PDF generation?

**Comment by bollwyvl** [comment]
This work can be thought of as Themes 1.0. All config will be at the _whole presentation_ level, without precluding the later customization of individual slides and regions.

## Technical Challenges

> this might grow

- [ ] theme loading (new server route)
  - [ ] for the time being, define these as python (conda/pip) packages
  - [ ] distribute the fonts
- [ ] data model for themes
- [ ] pick theme presets in web UI
  - [ ] initial thought: "style guide" UI
- [ ] actually update elements in presentation!
  - [ ] make sure it turns off!
- [ ] off-line build with embedded fonts
- [ ] verify functionality with offline viewer (ghost.py CSS)
- [ ] build themes!
  - [x] `null`: doesn't do anything
  - [ ] `base:light`: extremely minimal, most of the opinions from notebook, except fonts (helvetica and arial, begone!)
  - [ ] `base:dark`: inverted from above (maybe the jupyter orange instead of the blue, etc). 
  - [ ] `anaconda:watermark`: adds the _powered by anaconda_ watermark to a corner slot
  - [ ] `continuum:corp`: the continuum presentation template. lots to do.
