### ISSUE TITLE
Remote (Anaconda Server/Cloud) information

### ISSUE THREAD

**Issue by mmarchetti** [Anaconda-Server/anaconda-nb-extensions#50]
Remote information - timeboxed so dropping to 2 story points
- [x] Anaconda Enterprise connection
- [ ] New tab to present this information

**Comment by malev** [comment]
First steps in https://github.com/Anaconda-Server/nb_anacondacloud

**Comment by stephenakearns** [comment]
Hi @malev - can you move this to the in-progress pipeline?

**Comment by malev** [comment]
Commits:

* https://github.com/Anaconda-Server/nb_anacondacloud/commit/7d3e26018de9a7cfb42b7b35c284bca5df706b6d
* https://github.com/Anaconda-Server/nb_anacondacloud/commit/92859696ed3de55e7e0e65adfb73630cd28e0c3a

**Comment by malev** [comment]
@mmarchetti instead of having a new tab, I've added two icons (see attached). So far you can:

* Upload a notebook
* Select the organization to upload
* Attach the environment

What are we missing?

<img width="163" alt="screen shot 2015-12-23 at 10 09 17 am" src="https://cloud.githubusercontent.com/assets/55977/11980032/638baea6-a95d-11e5-857c-d6263c5c1d99.png">

**Comment by damianavila** [comment]
Closing beause this is complete by `nb_anacondacloud`.
